package in.gravitykerala.universityofcalicut;


import java.util.HashSet;
import java.util.Set;

/**
 * Created by Prakash on 18/07/2015.
 */
public interface GravitySupport {
    String KEY_SELECTED_COURSE_ID = "selected_course";
    String KEY_SELECTED_DEPARTMENT_ID = "selected_department";
    String KEY_DISTANCE_EDUCATION_NEEDED = "distance_status";
    String KEY_VC_DESK_NEEDED = "vc_desk_status";
    String KEY_UOC_NEWS_NEEDED = "uoc_news";
    String KEY_UOC_ORDERS_NEEDED = "uoc_orders";
    String KEY_PREFERENCE_ID = "in.gravitykerala.universityofcalicut";


    String TAG_NOTIFICATION_COMMON = "NOTIFICATION_UOC_COMMON";//"NOTIFICATION_UOC_COMMON";

    String CLOUD_SERVICE_URI = "https://universityofcalicut.azure-mobile.net/";
    String CLOUD_SERVICE_KEY = "XWXXhaCoiYqzzERpfsqnhpJuQBgCAw42";
//      MobileServiceClient mClient = null;

    String TAG_COMMON_DISTANCE = "DISTANCE:"; //Should be put before all distance related tags

    String TAG_COMMON_EXAM = "EXAM:"; //Should be put before all Pareeksha Bhavan related tags

    String TAG_NOTIFICATION_VC_DESK = "NOTIFICATION_UOC_VCDESK";
    String TAG_NOTIFICATION_NEWS = "NOTIFICATION_UOC_NEWS";
    String TAG_NOTIFICATION_ORDERS = "NOTIFICATION_UOC_ORDERS";

    String TAG_NOTIFICATION_EXAM_NOTIFICATIONS = "NOTIFICATION_EXAM_NOTIFICATIONS";
    String TAG_NOTIFICATION_EXAM_RESULT = "NOTIFICATION_EXAM_RESULT";
    String TAG_NOTIFICATION_EXAM_TIMETABLE = "NOTIFICATION_EXAM_TIMETABLE";

    String TAG_NOTIFICATION_DISTANCE_CONTACT_CLASS = "NOTIFICATION_DISTANCE_CONTACT_CLASS";
    String TAG_NOTIFICATION_DISTANCE_NOTIFICATIONS = "NOTIFICATION_DISTANCE_NOTIFICATIONS";
    String TAG_NOTIFICATION_DISTANCE_STUDY_MATERIAL = "NOTIFICATION_DISTANCE_STUDY_MATERIAL";
    String TAG_NOTIFICATION_DISTANCE_QUESTION_BANK = "NOTIFICATION_DISTANCE_QUESTION_BANK";

    String ID_NOTIFICATION_VC_DESK = "NOTIFICATION_VC_DESK";
    String ID_NOTIFICATION_NEWS = "NOTIFICATION_NEWS";
    String ID_NOTIFICATION_ORDERS = "NOTIFICATION_ORDERS";

    String ID_NOTIFICATION_EXAM_NOTIFICATIONS = "EXAM_NOTIFICATIONS";
    String ID_NOTIFICATION_EXAM_RESULT = "EXAM_RESULT";
    String ID_NOTIFICATION_EXAM_TIMETABLE = "EXAM_TIMETABLE";

    String ID_NOTIFICATION_DISTANCE_NOTIFICATION = "DISTANCE_NOTIFICATION";
    String ID_NOTIFICATION_DISTANCE_CONTACT_CLASS = "DISTANCE_CONTACT_CLASS";
    String ID_NOTIFICATION_DISTANCE_STUDY_MATERIAL = "DISTANCE_STUDY_MATERIAL";
    String ID_NOTIFICATION_DISTANCE_QUESTION_BANK = "DISTANCE_QUESTION_BANK";

    String KEY_NOTIFICATION_TYPE = "NOTIFICATION_TYPE";



}
